<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acceso · EDUTECH</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-950 antialiased"><main class="grid min-h-screen lg:grid-cols-2">
<section class="relative hidden overflow-hidden lg:flex lg:flex-col lg:justify-between lg:p-14"><div class="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(45,212,191,.2),transparent_32%),radial-gradient(circle_at_85%_80%,rgba(59,130,246,.18),transparent_35%)]"></div><div class="relative flex items-center gap-3 text-white"><span class="grid size-11 place-items-center rounded-xl bg-teal-400 text-xl font-black text-slate-950">E</span><span class="text-xl font-black tracking-[.2em]">EDUTECH</span></div><div class="relative max-w-xl"><p class="mb-5 text-sm font-bold uppercase tracking-[.25em] text-teal-300">Gestión educativa inteligente</p><h1 class="text-5xl font-bold leading-tight text-white">Todo tu ecosistema académico, en un solo lugar.</h1><p class="mt-6 text-lg leading-relaxed text-slate-400">Organiza estudiantes, programas y matrículas con información clara para tomar mejores decisiones.</p></div><p class="relative text-sm text-slate-500">© {{ date('Y') }} EDUTECH</p></section>
<section class="flex items-center justify-center bg-white p-6 sm:p-12"><div class="w-full max-w-md"><div class="mb-10 lg:hidden"><span class="text-xl font-black tracking-[.2em] text-slate-950">EDUTECH</span></div><p class="text-sm font-bold uppercase tracking-widest text-teal-600">Bienvenido</p><h2 class="mt-2 text-3xl font-bold tracking-tight">Inicia sesión</h2><p class="mt-3 text-slate-500">Ingresa tus credenciales para continuar.</p>
<form method="POST" action="{{ route('login.store') }}" class="mt-9 space-y-5">@csrf
<div><label class="label" for="email">Correo electrónico</label><input class="input" id="email" name="email" type="email" value="{{ old('email') }}" required autofocus placeholder="nombre@edutech.com">@error('email')<p class="error">{{ $message }}</p>@enderror</div>
<div><div class="flex justify-between"><label class="label" for="password">Contraseña</label></div><input class="input" id="password" name="password" type="password" required placeholder="••••••••"></div>
<label class="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="remember" class="rounded border-slate-300 text-teal-600"> Mantener sesión iniciada</label>
<button class="btn-primary w-full justify-center py-3">Ingresar al panel</button></form><p class="mt-8 text-center text-xs text-slate-400">Acceso exclusivo para personal autorizado.</p></div></section>
</main></body></html>
