@extends('layouts.app', ['title'=>'Dashboard'])
@section('content')
<div class="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div class="mb-5 flex h-16 items-center"><x-brand-logo :organization="auth()->user()->organization" class="max-h-16 max-w-56" /></div><p class="text-slate-500">Resumen operativo con información confirmada</p><h2 class="mt-1 text-2xl font-black">Hola, {{ explode(' ', auth()->user()->name)[0] }}</h2></div><div class="flex flex-wrap gap-2"><a class="btn-primary" href="{{ route('portfolio.index') }}">Registrar pago</a><a class="btn-secondary" href="{{ route('students.index') }}">Buscar estudiante</a><a class="btn-secondary" href="{{ route('reports.show','overdue') }}">Cartera vencida</a><a class="btn-secondary" href="{{ route('reports.show','revenue') }}">Ver recaudo</a><a class="btn-secondary" href="{{ route('reports.index') }}">Ver informes</a></div></div>
@php($kpis=[['Estudiantes activos',$activeStudents,false],['Matrículas activas',$activeEnrollments,false],['Cartera pendiente',$portfolioPending,true],['Cartera vencida',$overduePortfolio,true],['Recaudo de hoy',$todayRevenue,true],['Recaudo de la semana',$weekRevenue,true],['Recaudo del mes',$monthRevenue,true],['Estudiantes con saldo pendiente',$studentsWithBalance,false]])
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($kpis as [$label,$value,$money])<div class="card"><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-3 text-3xl font-black">{{ $money ? '$'.number_format($value,0,',','.') : number_format($value) }}</p></div>@endforeach</div>
<p class="mt-4 text-xs text-amber-700">La cartera vencida y la mora solo incluyen obligaciones con fecha de vencimiento confiable.</p>
<div class="mt-7 grid gap-6 xl:grid-cols-3"><section class="card"><h3 class="font-black">Últimos pagos registrados</h3><div class="mt-4 space-y-3">@forelse($recentPayments as $payment)<div class="flex justify-between gap-3 border-b border-slate-100 pb-3"><div><p class="font-semibold">{{ $payment->enrollment->student->full_name }}</p><p class="text-xs text-slate-500">{{ $payment->payment_date?->format('d/m/Y') ?? 'Fecha no disponible' }}</p></div><strong>${{ number_format($payment->amount,0,',','.') }}</strong></div>@empty<p class="text-sm text-slate-500">Todavía no hay pagos registrados.</p>@endforelse</div></section><section class="card"><h3 class="font-black">Resumen de cartera</h3><dl class="mt-4 space-y-4"><div><dt>Al día</dt><dd>{{ max($activeEnrollments-$studentsWithBalance,0) }} matrículas</dd></div><div><dt>Con saldo pendiente</dt><dd>{{ $studentsWithBalance }} estudiantes</dd></div><div><dt>Vencida</dt><dd>{{ $delinquentStudents }} estudiantes · ${{ number_format($overduePortfolio,0,',','.') }}</dd></div></dl><a class="mt-5 inline-block text-sm font-bold text-teal-700" href="{{ route('portfolio.index') }}">Abrir cartera →</a></section><section class="card"><h3 class="font-black">Recaudo por periodo</h3><dl class="mt-4 space-y-4"><div><dt>Hoy</dt><dd>${{ number_format($todayRevenue,0,',','.') }}</dd></div><div><dt>Semana</dt><dd>${{ number_format($weekRevenue,0,',','.') }}</dd></div><div><dt>Mes</dt><dd>${{ number_format($monthRevenue,0,',','.') }}</dd></div></dl></section></div>
<div class="mt-7 grid gap-6 lg:grid-cols-2"><section class="card"><h3 class="font-black">Grupos con mayor saldo pendiente</h3><div class="mt-4 space-y-3">@forelse($topGroups as $group)<div class="flex justify-between gap-3"><span>{{ $group->course_name }} · {{ $group->name }}</span><strong>${{ number_format($group->pending,0,',','.') }}</strong></div>@empty<p class="text-sm text-slate-500">No hay saldos pendientes para mostrar.</p>@endforelse</div></section><section class="card"><h3 class="font-black">Alertas importantes</h3><div class="mt-4 space-y-3"><a class="flex justify-between rounded-xl bg-amber-50 p-4" href="{{ route('enrollment-reviews.index') }}"><span>Datos pendientes de revisión</span><strong>{{ $reviewAlerts }}</strong></a><a class="flex justify-between rounded-xl bg-rose-50 p-4" href="{{ route('reports.show','overdue') }}"><span>Estudiantes con mora confirmada</span><strong>{{ $delinquentStudents }}</strong></a></div></section></div>
<div class="card mt-7"><div class="mb-5 flex items-center justify-between"><div><h3 class="font-bold">Matrículas recientes</h3><p class="text-sm text-slate-500">Últimos registros</p></div><a href="{{ route('enrollments.index') }}" class="text-sm font-semibold text-teal-700">Ver todas →</a></div><div class="overflow-x-auto"><table><thead><tr><th>Estudiante</th><th>Curso / grupo</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>@forelse($recentEnrollments as $item)<tr><td><a class="font-semibold hover:text-teal-700" href="{{ route('students.show',$item->student) }}">{{ $item->student->full_name }}</a></td><td>{{ $item->group->course->name }} · {{ $item->group->name }}</td><td>{{ $item->enrollment_date?->format('d/m/Y') ?? 'Sin fecha' }}</td><td><span class="badge status-{{ $item->status->value }}">{{ $item->status->label() }}</span></td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-slate-400">Aún no hay matrículas registradas.</td></tr>@endforelse</tbody></table></div></div>
@endsection
