@extends('layouts.app', ['title'=>'Nueva matrícula'])
@section('content')
<div class="mx-auto max-w-3xl"><div class="mb-7"><a href="{{ route('enrollments.index') }}" class="text-sm font-semibold text-slate-500">← Matrículas</a><h2 class="mt-4 text-2xl font-bold">Registrar matrícula</h2><p class="mt-1 text-slate-500">Asigna un estudiante a un grupo y define las condiciones iniciales.</p></div>
<form method="POST" action="{{ route('enrollments.store') }}" class="card space-y-6">@csrf
<div><label class="label">Estudiante</label><select name="student_id" class="input" required><option value="">Seleccionar estudiante</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(old('student_id',(string)$selectedStudent)===$student->id)>{{ $student->last_name }}, {{ $student->first_name }} · {{ $student->document_number }}</option>@endforeach</select>@error('student_id')<p class="error">{{ $message }}</p>@enderror</div>
<div><label class="label">Grupo / curso</label><select name="group_id" class="input" required><option value="">Seleccionar grupo</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected(old('group_id')===$group->id)>{{ $group->course->name }} · {{ $group->name }} ({{ $group->schedule }})</option>@endforeach</select>@error('group_id')<p class="error">{{ $message }}</p>@enderror</div>
<div class="grid gap-5 sm:grid-cols-2"><div><label class="label">Fecha de matrícula</label><input type="date" name="enrollment_date" class="input" required value="{{ old('enrollment_date',date('Y-m-d')) }}"></div><div><label class="label">Inicio de facturación</label><input type="date" name="billing_start_date" class="input" required value="{{ old('billing_start_date',date('Y-m-d')) }}"></div><div><label class="label">Valor acordado</label><input type="number" min="0" step="0.01" name="agreed_amount" class="input" required value="{{ old('agreed_amount') }}" placeholder="0"></div><div><label class="label">Estado</label><select name="status" class="input">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status','pending')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div></div>
<div><label class="label">Observaciones</label><textarea name="notes" rows="3" class="input">{{ old('notes') }}</textarea></div>
@if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">Revisa la información ingresada.</div>@endif
<div class="flex justify-end gap-3 border-t border-slate-100 pt-6"><a href="{{ route('enrollments.index') }}" class="btn-secondary">Cancelar</a><button class="btn-primary">Registrar matrícula</button></div></form></div>
@endsection
