@extends('layouts.app', ['title' => $title])
@section('content')
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a class="text-sm font-bold text-slate-500" href="{{ route('reports.index') }}">← Informes</a><h2 class="mt-3 text-2xl font-black">{{ $title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $description }}</p></div><div class="flex gap-2"><button class="btn-secondary" onclick="window.print()">Imprimir</button><a class="btn-primary" href="{{ request()->fullUrlWithQuery(['format'=>'csv']) }}">Exportar CSV</a></div></div>
<form method="GET" class="card mb-6 grid gap-3 md:grid-cols-2 xl:grid-cols-5 print:hidden"><label class="text-xs font-bold text-slate-500">Fecha desde<input class="input mt-1" type="date" name="from" value="{{ request('from') }}"></label><label class="text-xs font-bold text-slate-500">Fecha hasta<input class="input mt-1" type="date" name="to" value="{{ request('to') }}"></label><select class="input" name="group_id"><option value="">Todos los cursos/grupos</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected(request('group_id')===$group->id)>{{ $group->course->name }} — {{ $group->name }}</option>@endforeach</select><select class="input" name="student_id"><option value="">Todos los estudiantes</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(request('student_id')===$student->id)>{{ $student->full_name }}</option>@endforeach</select><div class="flex gap-2"><select class="input" name="status"><option value="">Todos los estados</option>@foreach(\App\Enums\EnrollmentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ \App\Support\Status::label($status) }}</option>@endforeach</select><button class="btn-primary">Filtrar</button><a class="btn-secondary" href="{{ route('reports.show',$report) }}">Limpiar</a></div></form>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($totals as $label=>$value)<div class="card"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-black">{{ str_contains(strtolower($label),'total') || in_array($label,['Pagado','Saldo','Valor acordado'],true) ? '$'.number_format($value,0,',','.') : number_format($value) }}</p></div>@endforeach</div>
@if($methodTotals->isNotEmpty())<div class="card mb-6"><h3 class="font-black">Recaudo por método de pago</h3><div class="mt-4 flex flex-wrap gap-3">@foreach($methodTotals as $method=>$amount)<span class="rounded-xl bg-slate-50 px-4 py-3"><strong>{{ \App\Support\Status::paymentMethod($method) }}</strong> · ${{ number_format($amount,0,',','.') }}</span>@endforeach</div></div>@endif
@if(in_array($report,['overdue','high-delinquency'],true))<p class="mb-4 text-xs text-amber-700">Solo se incluyen obligaciones con fecha de vencimiento confiable.</p>@endif
<div class="card overflow-x-auto p-0"><table><thead><tr>@if(in_array($report,['revenue','student-payments']))<th>Fecha</th><th>Estudiante</th><th>Curso/grupo</th><th>Método</th><th>Referencia</th><th class="text-right">Valor</th>@elseif($report==='overdue')<th>Vencimiento</th><th>Estudiante</th><th>Curso/grupo</th><th>Cuota</th><th class="text-right">Valor</th>@elseif($report==='groups')<th>Curso</th><th>Grupo / horario</th><th>Matrículas</th><th class="text-right">Valor acordado</th>@elseif($report==='high-delinquency')<th>Estudiante</th><th>Curso/grupo</th><th>Obligaciones</th><th class="text-right">Total vencido</th>@else<th>Estudiante</th><th>Curso/grupo</th><th>Estado</th><th class="text-right">Acordado</th><th class="text-right">Pagado</th><th class="text-right">Saldo</th>@endif</tr></thead><tbody>
@forelse($records as $record)
@if(in_array($report,['revenue','student-payments']))<tr><td>{{ $record->payment_date?->format('d/m/Y') ?? 'Sin fecha' }}</td><td>{{ $record->enrollment->student->full_name }}</td><td>{{ $record->enrollment->group->course->name }} / {{ $record->enrollment->group->name }}</td><td>{{ \App\Support\Status::paymentMethod($record->method) }}</td><td>{{ $record->reference ?: '—' }}</td><td class="text-right font-bold">${{ number_format($record->amount,0,',','.') }}</td></tr>
@elseif($report==='overdue')<tr><td>{{ $record->due_date->format('d/m/Y') }}</td><td>{{ $record->enrollment->student->full_name }}</td><td>{{ $record->enrollment->group->course->name }} / {{ $record->enrollment->group->name }}</td><td>#{{ $record->installment_number }}</td><td class="text-right font-bold text-rose-700">${{ number_format($record->amount,0,',','.') }}</td></tr>
@elseif($report==='groups')<tr><td>{{ $record->course->name }}</td><td>{{ $record->name }}<div class="text-xs text-slate-500">{{ $record->schedule }}</div></td><td>{{ $record->enrollments_count }}</td><td class="text-right">${{ number_format($record->agreed_total,0,',','.') }}</td></tr>
@elseif($report==='high-delinquency')<tr><td>{{ $record->student->full_name }}</td><td>{{ $record->group->course->name }} / {{ $record->group->name }}</td><td><span class="badge bg-rose-50 text-rose-700">{{ $record->overdue_count }} vencidas</span></td><td class="text-right font-bold text-rose-700">${{ number_format($record->overdue_amount,0,',','.') }}</td></tr>
@else<tr><td>{{ $record->student->full_name }}</td><td>{{ $record->group->course->name }} / {{ $record->group->name }}</td><td><span class="badge status-{{ $record->status->value }}">{{ $record->status->label() }}</span></td><td class="text-right">{{ $record->agreed_amount === null ? 'Pendiente' : '$'.number_format($record->agreed_amount,0,',','.') }}</td><td class="text-right">${{ number_format($record->total_paid,0,',','.') }}</td><td class="text-right font-bold">{{ $record->balance === null ? 'No calculable' : '$'.number_format($record->balance,0,',','.') }}</td></tr>@endif
@empty<tr><td colspan="7" class="py-12 text-center"><strong>No hay resultados</strong><div class="mt-1 text-slate-400">Prueba ajustando los filtros seleccionados.</div></td></tr>@endforelse
</tbody></table></div><div class="mt-5 print:hidden">{{ $records->links() }}</div>
@endsection
