@extends('layouts.app', ['title'=>$student->exists ? 'Editar estudiante' : 'Nuevo estudiante'])
@section('content')
<div class="mx-auto max-w-5xl"><div class="mb-7"><a href="{{ $student->exists ? route('students.show',$student) : route('students.index') }}" class="text-sm font-semibold text-slate-500">← Volver</a><h2 class="mt-4 text-2xl font-bold">{{ $student->exists ? 'Editar estudiante' : 'Registrar estudiante' }}</h2><p class="mt-1 text-slate-500">Completa los datos personales y de contacto.</p></div>
<form method="POST" action="{{ $student->exists ? route('students.update',$student) : route('students.store') }}" class="card">@csrf @if($student->exists) @method('PUT') @endif
<div class="mb-8"><h3 class="border-b border-slate-100 pb-3 font-bold">Identificación</h3><div class="mt-5 grid gap-5 sm:grid-cols-3"><div><label class="label">Tipo de documento</label><select name="document_type" class="input" required>@foreach(['TI','CC','RC','CE','PA'] as $type)<option @selected(old('document_type',$student->document_type)===$type)>{{ $type }}</option>@endforeach</select></div><div class="sm:col-span-2"><label class="label">Número de documento</label><input name="document_number" class="input" required value="{{ old('document_number',$student->document_number) }}">@error('document_number')<p class="error">{{ $message }}</p>@enderror</div></div></div>
<div class="mb-8"><h3 class="border-b border-slate-100 pb-3 font-bold">Información personal</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="label">Nombres</label><input name="first_name" class="input" required value="{{ old('first_name',$student->first_name) }}">@error('first_name')<p class="error">{{ $message }}</p>@enderror</div><div><label class="label">Apellidos</label><input name="last_name" class="input" required value="{{ old('last_name',$student->last_name) }}"></div><div><label class="label">Fecha de nacimiento</label><input type="date" name="birth_date" class="input" value="{{ old('birth_date',$student->birth_date?->format('Y-m-d')) }}"></div><div><label class="label">Género</label><input name="gender" class="input" value="{{ old('gender',$student->gender) }}" placeholder="Opcional"></div></div></div>
<div class="mb-8"><h3 class="border-b border-slate-100 pb-3 font-bold">Contacto y ubicación</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="label">Correo</label><input type="email" name="email" class="input" value="{{ old('email',$student->email) }}"></div><div><label class="label">Teléfono</label><input name="phone" class="input" value="{{ old('phone',$student->phone) }}"></div><div class="sm:col-span-2"><label class="label">Dirección</label><input name="address" class="input" value="{{ old('address',$student->address) }}"></div><div><label class="label">Municipio</label><select name="municipality_id" class="input"><option value="">Seleccionar</option>@foreach($municipalities as $item)<option value="{{ $item->id }}" @selected(old('municipality_id',$student->municipality_id)===$item->id)>{{ $item->name }}, {{ $item->department }}</option>@endforeach</select></div><div><label class="label">Sede</label><select name="campus_id" class="input"><option value="">Seleccionar</option>@foreach($campuses as $item)<option value="{{ $item->id }}" @selected(old('campus_id',$student->campus_id)===$item->id)>{{ $item->name }}</option>@endforeach</select></div><div><label class="label">Estado</label><select name="active" class="input"><option value="1" @selected(old('active',$student->active ?? true))>Activo</option><option value="0" @selected(old('active',$student->active ?? true) === false)>Inactivo</option></select></div></div></div>
@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">Revisa los campos marcados. Hay {{ $errors->count() }} error(es).</div>@endif
<div class="flex justify-end gap-3 border-t border-slate-100 pt-6"><a class="btn-secondary" href="{{ route('students.index') }}">Cancelar</a><button class="btn-primary">{{ $student->exists ? 'Guardar cambios' : 'Crear estudiante' }}</button></div></form></div>
@endsection
